.PHONY: clean All

All:
	@echo "----------Building project:[ Lagrang - Debug ]----------"
	@cd "Lagrang" && "$(MAKE)" -f  "Lagrang.mk"
clean:
	@echo "----------Cleaning project:[ Lagrang - Debug ]----------"
	@cd "Lagrang" && "$(MAKE)" -f  "Lagrang.mk" clean
